dist: bionic
sudo: required
language: java
services:
  - docker

addons:
  sonarcloud:
    organization: "zorck97"
    token:
      secure: "WDIbM9J1chRH2kKW4rFF9/FWaDwqdJg6bVJ85DV2aQ9UfkP7l9OvU1mTKVoWdrXXkvxuEhEr23Ubnp2HDf1zIJ+hM/WIKND6fOv1qw7O8tWEs2JYR4CUEF+vhtuSxhb5BZnxLpmmZw0C+Rln82wHbxrrO4zXN7Wa+37+a/ir18p0CaJ4txTxUX2LCoyVeBoyynexKq1v9WWRHlb+t4wGrjp55fr6GFzhDZoRgjAZ6Jy6QqV9YLG7yAqlikoKLT4Pvd7Yy+iqqmL7cbyMcWMrpJ+m8aJhC/kIfA3K34H8hT5cYfAXyLv1iTzw4Axn5Gelv45R/L6u0YcPjZPog+FdR4cIfc+QyBdspo1lEBIOLc21Pl2Jv3/F7CpD5hdnyRVHZLTk6mgW0aEIqgshEvJ6E4rlQCtgAlS6vKIN/OWF8eeQOnEc78aaCEDaBHASH/RQTkQqMogy1nKvaRWW66UYzaceU0rRmWcxKhFdj2gZPyAA6OYJIP5jaoxSrVRsUUY539gfbbYEuMsGdC4cHVaZVX/wnoJD+1s7OqyT/6cIfikm7rA3u7EbXiPrhuI9AwK/i/20CBqDz/9MRsE48GGEucPrnYX02O0CfoOtk7rSZ6n39iZWFTgvoc+GIVupqjokkuo9bPlGPZwWLNVIYaVbrlJSL9qqNsOIE+/E51AQPSA="

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
    - "$HOME/.cache/trivy"

before_install:
  - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
  - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz

script:
  - ./mvnw clean compile
  - ./mvnw test
  - ./mvnw org.owasp:dependency-check-maven:check
  - ./mvnw verify
  - ./mvnw jib:dockerBuild
  - ./trivy --exit-code 0 --severity CRITICAL --no-progress myimage:latest
