dist: bionic
sudo: required
language: java
services:
  - docker

addons:
  sonarcloud:
    organization: "odc"
    token:
      secure: ""

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
    - "$HOME/.cache/trivy"

before_install:
  - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
  - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz

jobs:
  include:
    - stage: Compile
      script: ./mvnw clean compile
    - stage: Test
      script: ./mvnw test
    - stage: Software Dependency Check
      script: ./mvnw org.owasp:dependency-check-maven:check
    - stage: Integration Tests
      script: ./mvnw verify
    - stage: Build docker image
      script: ./mvnw jib:dockerBuild
    - stage: Docker security scan
      script: ./trivy --exit-code 0 --severity CRITICAL --no-progress myimage:latest
